import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import "../globals.css";



export const metadata = {
  title: "Smart Med Appointments",
  description: "Generated by Team 5",
};

export default function RootLayout({ children }) {
  return (
    <div >
      <NextAuthProvider>
        <div
         
        >
          {/* <TanstackProvider> */}
            <Navbar />
            <div className="min-h-screen">

            {children}
            </div>
            <Toaster />
            <Footer></Footer>
            {/* <ReactQueryDevtools initialIsOpen={false}ss /> */}
          {/* </TanstackProvider> */}
        </div>
      </NextAuthProvider>
    </div>
  );
}
